### ISSUE TITLE
Rolling friction bug persistent with bullet 2.89

### ISSUE THREAD

**Issue by rolfvdhulst** [RoboTeamTwente/roboteam_mimir#45]
https://github.com/bulletphysics/bullet3/issues/2117 is significantly affecting ball movement, the rolling friction approximation is still not working.

**Comment by erwincoumans** [comment]
The rolling friction issue is fixed for btMultiBody, not btRigidBody. Are you using btMultiBody?

**Comment by rolfvdhulst** [comment]
@erwincoumans I was indeed using btRigidBody, thanks for the heads up! I must say I am quite impressed and happy with Bullet so far :) Merry Christmas!

**Comment by rolfvdhulst** [comment]
@erwincoumans No i was not, thanks for clarifying (and have a merry christmas!). I replied on the forum post too but you can see that as solved.

**Comment by erwincoumans** [comment]
Good luck! I strongly suggest you try out PyBullet as well and do some prototyping in Python and URDF, even if you want to use C++. See its [Quickstart Guide](https://docs.google.com/document/d/10sXEhzFRSnvFcl3XxNGhnD4N2SedqwdAvK3dsihxVUA/edit#heading=h.2ye70wns7io3). After you are satisfied with the Python prototype, you can learn from the PyBullet code, which is mostly code in the 'examples' folder. In addition, you could try out the BulletRobotics [C++ API,](https://github.com/bulletphysics/bullet3/blob/master/examples/SharedMemory/b3RobotSimulatorClientAPI_NoDirect.h) which is almost the same as the PyBullet API. 

(in Google Robotics, we mostly use the PyBullet Python API)

Merry Christmas :)

**Comment by rolfvdhulst** [comment]
@erwincoumans Just to follow up, I am using btMultiBody now and everything is working fine. Thanks for your help! However, I did need to sacrifice a lot of performance (almost a factor ~2 for just using MultiBodyDynamicsWorld). The intention is for this project to be used in machine learning efforts, so if at any time this is also fixed for the sphere in btRigidBody, please let me know!
